BEGIN;

DROP VIEW public.vw_attendance_summary;
DROP VIEW public.vw_internship_assignment_details;
DROP VIEW public.vw_upcoming_interviews;
DROP VIEW public.vw_referral_details;
DROP VIEW public.vw_application_details;
DROP VIEW public.vw_opportunity_summary;
DROP VIEW public.vw_student_profile_details;

DROP TRIGGER trg_assignment_history_append_only ON public.internship_assignment_status_history;
DROP TRIGGER trg_referral_history_append_only ON public.referral_status_history;
DROP TRIGGER trg_application_history_append_only ON public.application_status_history;
DROP TRIGGER trg_account_history_append_only ON public.user_account_status_history;
DROP TRIGGER trg_assignment_status_history ON public.internship_assignment;
DROP TRIGGER trg_referral_status_history ON public.referral;
DROP TRIGGER trg_application_status_history ON public.application;
DROP TRIGGER trg_user_account_status_history ON public.user_account;
DROP TRIGGER trg_internship_feedback_workflow ON public.internship_feedback;
DROP TRIGGER trg_attendance_record_derive ON public.attendance_record;
DROP TRIGGER trg_internship_assignment_workflow ON public.internship_assignment;
DROP TRIGGER trg_interview_workflow ON public.interview;
DROP TRIGGER trg_application_referral_consistency ON public.application;
DROP TRIGGER trg_referral_consistency ON public.referral;
DROP TRIGGER trg_referral_workflow ON public.referral;
DROP TRIGGER trg_application_workflow ON public.application;
DROP TRIGGER trg_opportunity_status_transition ON public.opportunity;
DROP TRIGGER trg_company_industry_valid ON public.company;
DROP TRIGGER trg_industry_custom_flag_valid ON public.industry;
DROP TRIGGER trg_student_preferred_industry_valid ON public.student_preferred_industry;
DROP TRIGGER trg_peso_account_profile_integrity ON public.peso_personnel;
DROP TRIGGER trg_company_account_profile_integrity ON public.company;
DROP TRIGGER trg_student_account_profile_integrity ON public.student;
DROP TRIGGER trg_user_account_profile_integrity ON public.user_account;
DROP TRIGGER trg_peso_personnel_profile_account ON public.peso_personnel;
DROP TRIGGER trg_company_profile_account ON public.company;
DROP TRIGGER trg_student_profile_account ON public.student;
DROP TRIGGER trg_user_account_status_transition ON public.user_account;
DROP TRIGGER trg_internship_feedback_updated_at ON public.internship_feedback;
DROP TRIGGER trg_attendance_record_updated_at ON public.attendance_record;
DROP TRIGGER trg_internship_assignment_updated_at ON public.internship_assignment;
DROP TRIGGER trg_interview_updated_at ON public.interview;
DROP TRIGGER trg_referral_updated_at ON public.referral;
DROP TRIGGER trg_peso_personnel_updated_at ON public.peso_personnel;
DROP TRIGGER trg_application_updated_at ON public.application;
DROP TRIGGER trg_opportunity_updated_at ON public.opportunity;
DROP TRIGGER trg_company_updated_at ON public.company;
DROP TRIGGER trg_student_requirement_submission_updated_at ON public.student_requirement_submission;
DROP TRIGGER trg_requirement_type_updated_at ON public.requirement_type;
DROP TRIGGER trg_industry_updated_at ON public.industry;
DROP TRIGGER trg_internship_preference_updated_at ON public.internship_preference;
DROP TRIGGER trg_student_academic_information_updated_at ON public.student_academic_information;
DROP TRIGGER trg_student_updated_at ON public.student;
DROP TRIGGER trg_user_account_updated_at ON public.user_account;

DROP FUNCTION public.fn_block_status_history_mutation();
DROP FUNCTION public.fn_record_status_history();
DROP FUNCTION public.fn_validate_feedback();
DROP FUNCTION public.fn_derive_attendance();
DROP FUNCTION public.fn_validate_assignment();
DROP FUNCTION public.fn_validate_interview();
DROP FUNCTION public.fn_check_referral_consistency();
DROP FUNCTION public.fn_validate_referral();
DROP FUNCTION public.fn_validate_application();
DROP FUNCTION public.fn_validate_opportunity_transition();
DROP FUNCTION public.fn_validate_company_industry();
DROP FUNCTION public.fn_validate_industry_custom_flag();
DROP FUNCTION public.fn_validate_student_preferred_industry();
DROP FUNCTION public.fn_validate_profile_account();
DROP FUNCTION public.fn_check_account_profile_integrity();
DROP FUNCTION public.fn_validate_account_status_transition();
DROP FUNCTION public.fn_current_status_actor();
DROP FUNCTION public.fn_set_updated_at();

DROP TABLE public.internship_assignment_status_history;
DROP TABLE public.referral_status_history;
DROP TABLE public.application_status_history;
DROP TABLE public.user_account_status_history;
DROP TABLE public.internship_feedback;
DROP TABLE public.attendance_record;
DROP TABLE public.internship_assignment;
DROP TABLE public.interview;
DROP TABLE public.referral;
DROP TABLE public.peso_personnel;
DROP TABLE public.application;
DROP TABLE public.opportunity;
DROP TABLE public.company;
DROP TABLE public.student_requirement_submission;
DROP TABLE public.requirement_type;
DROP TABLE public.student_preferred_industry;
DROP TABLE public.industry;
DROP TABLE public.internship_preference;
DROP TABLE public.student_academic_information;
DROP TABLE public.student;
DROP TABLE public.user_account;

DROP TYPE public.interview_mode_enum;
DROP TYPE public.work_arrangement_enum;
DROP TYPE public.rendered_hours_status_enum;
DROP TYPE public.time_in_status_enum;
DROP TYPE public.assignment_status_enum;
DROP TYPE public.student_response_enum;
DROP TYPE public.company_response_enum;
DROP TYPE public.referral_status_enum;
DROP TYPE public.application_status_enum;
DROP TYPE public.work_schedule_enum;
DROP TYPE public.opportunity_status_enum;
DROP TYPE public.company_type_enum;
DROP TYPE public.year_level_enum;
DROP TYPE public.inquiry_method_enum;
DROP TYPE public.user_role_enum;
DROP TYPE public.account_status_enum;

COMMIT;
